name: 游닢 Hj칛lp
description: Du beh칬ver hj칛lp att ladda ned en specifik video
labels:
  - help wanted

body:
  - type: checkboxes
    attributes:
      label: Innan du skickar in hj칛lpf칬rfr친gan
      description: 'Se till att du:'
      options:
        - label: Jag f칬rst친r att Privatkopiera och FFmpeg inte kan ladda hem vissa filmer som har extra kopieringsskydd och kryptering.
          required: true
        - label: Har kollat om det [redan finns en buggrapport](https://github.com/stefansundin/privatkopiera/issues) om det h칛r.
          required: true
        - label: Har kollat om det [redan finns en diskussionstr친d](https://github.com/stefansundin/privatkopiera/discussions) om det h칛r.
          required: true
        - label: T칛nkt efter om det h칛r kanske passar b칛ttre som [en diskussionstr친d](https://github.com/stefansundin/privatkopiera/discussions).
          required: true

  - type: input
    attributes:
      label: L칛nk till video du beh칬ver hj칛lp med
      description: Om du har fler 칛n en l칛nk s친 l칛gg till de andra i f칛ltet nedanf칬r.
      placeholder: https://...
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Kryssa i den h칛r rutan om alla klipp p친 sidan har slutat fungera
      options:
        - label: Alla klipp p친 sidan har slutat fungera

  - type: textarea
    attributes:
      label: Beskriv vad som inte fungerar
    validations:
      required: true
